name: Chengwei's Words
author: Chengwei Yang
url: http://www.chengweiyang.cn
description: "{hello world}"
timezone: Asia/Chongqing

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
gems: [jekyll-paginate]
